name: Build and test

on: [push, pull_request]

env:
  GOLANGCI_LINT_VERSION: v1.55.2

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [stable, oldstable]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download and check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Install golangci-lint
        run: make validate

      - name: Run tests
        run: make test
